name: deploy

on:
    workflow_dispatch:
    
permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          ls
          pwd
          //go build -trimpath -ldflags="-s -w" -o "vaydns-client-${{ matrix.goos }}-${ARCH}${SUFFIX}" ./vaydns-client
          go build -trimpath -ldflags="-s -w" -o "vaydns-server-x" ./vaydns-server
          chmod +x vaydns-client-* vaydns-server-*
