name: deploy

on:
    workflow_dispatch:
    
permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          ls -alh
          ip a
          sudo iptables -t nat -I PREROUTING -i eth0 -p udp --dport 53 -j REDIRECT --to-ports 5300
          wget https://github.com/net2share/vaydns/releases/download/v0.2.7/vaydns-server-linux-amd64
          chmod +x vaydns-client-linux-amd64
          ls -alh
          ./vaydns-server-linux-amd64 -gen-key -privkey-file server.key -pubkey-file server.pub
          cat server.pub
          curl ifconfig.co
          
          pwd
