name: deploy

on:
    workflow_dispatch:
    
permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: |
          ls -alh
          wget https://github.com/net2share/vaydns/releases/download/v0.2.7/vaydns-client-linux-amd64
          ls -alh
          pwd
