name: Run Commands on Server

on:
    workflow_dispatch:

jobs:
  ssh-run:
    runs-on: ubuntu-latest

    steps:
      - name: Run commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 85.122.120.240
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
              ls -alh
              cd vaydns
              ls -alh
              cat server.pub
              pkill -f "vaydns-server"
              ncat -l -k -v 127.0.0.1 8000 &
              ./vaydns-server-* -udp :5300 -privkey-file server.key -mtu 1000 -domain t.vivatel.ir -upstream 127.0.0.1:8000
