name: Run Commands on Server

on:
    workflow_dispatch:

jobs:
  ssh-run:
    runs-on: ubuntu-latest

    steps:
      - name: Run commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 85.122.120.240
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
              ls -alh
              mkdir vaydns
              cd vaydns
              sudo iptables -t nat -I PREROUTING -i eth0 -p udp --dport 53 -j REDIRECT --to-ports 5300
              wget https://github.com/net2share/vaydns/releases/download/v0.2.7/vaydns-server-linux-amd64
              chmod +x vaydns-server-linux-amd64
              ls -alh
              ./vaydns-server-linux-amd64 -gen-key -privkey-file server.key -pubkey-file server.pub
              cat server.pub
              curl -4 ifconfig.me
              ./vaydns-server-* -help
