name: 66

on:
    workflow_dispatch:

jobs:
  ssh-run:
    runs-on: ubuntu-latest

    steps:
      - name: Run commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 66.135.23.133
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
              ls -alh
              cd gts/
              rm gp*
              wget https://github.com/hpishbin/s/raw/refs/heads/main/gpipeline
              chmod +x gpipeline
              ls -alh requests/
              ls -alh responses/
              # git config --global user.email "you@example.com"
              # git config --global user.name "Your Name"
              pwd
              ls -alh
              pkill -x gpipeline || true
              ./gpipeline --role server
