name: 66

on:
    workflow_dispatch:

jobs:
  ssh-run:
    runs-on: ubuntu-latest

    steps:
      - name: Run commands via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 66.135.23.133
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
        env:
          script: |
              ls -alh
              cd gts/
              pwd
              ls -alh
              mkdir responses requests
              cd responses
              ${{ secrets.ALKEY }}
              ls -alh
              #./gpipeline server
